plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docs/Scuba_diving_refs.md
  - docs/Seances_saison_2021_2022.md
  - docs/Seances_saison_2022_2023_PMT.md

title: Freediving Notes
description: Notes personnelles en apn√©e
theme: jekyll-theme-primer
